test:
  prototype-val: "Test hello world"

server:
  port: ${SERVER_PORT_SPRING:8080}
  shutdown: GRACEFUL

spring:
  jackson:
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSX

  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    username: sa
    password:
    url: jdbc:h2:file:./test;DB_CLOSE_DELAY=-1;

  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd'T'HH:mm:ss
      time: HH:mm:ss
